# Copyright (c) 2022-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: 🏗️ Build Websites

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: read

jobs:
  submodule:
    strategy:
      matrix:
        repo: [mkdocs-material-insiders, brand, i18n]
    uses: privacyguides/.github/.github/workflows/download-repo.yml@main
    with:
      repo: ${{ matrix.repo }}
    secrets:
      ACTIONS_SSH_KEY: ${{ secrets.ACTIONS_SSH_KEY }}

  build:
    needs: submodule
    strategy:
      matrix:
        lang: [es, fr, he, it, ko, nl, pt, ru, zh-Hant, zh-TW]
      fail-fast: false
    permissions:
      contents: read
    uses: privacyguides/privacyguides.org/.github/workflows/build.yml@main
    with:
      ref: main
      repo: 'privacyguides/privacyguides.org'
      lang: ${{ matrix.lang }}
      continue-on-error: true

  cleanup:
    if: ${{ always() }}
    needs: build
    uses: privacyguides/.github/.github/workflows/cleanup.yml@main
